spring:
  app:
    jwtSecret: s3cr37
    jwtExpirationMs: 36000000
  datasource:
    url: jdbc:postgresql://localhost:5432/ape_beats
    username: postgres
    password: ar4ebar4e
    driver-class-name: org.postgresql.Driver
